services:
  dynamic_iqa:
    image: dynamic_iqa_ex:latest
    container_name: dynamic_iqa
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ${HOME}/Dev/Datasets
        target: /dynamic_iqa_ex/Datasets
      - type: bind
        source: ./
        target: /dynamic_iqa_ex